package com.youtil.Common.Enums;


public enum AiProgress {
    WAITING, PROCESSING, FINISHED, ERROR,GET_COMMIT_DATA_FROM_GITHUB,COMMIT_ANALYSIS_START,SUPERVISOR_START,RESEARCH_TEAM_START,INTRODUCTION_START,CONCLUSION_START
}
