name: BE CD PROD

on:
  workflow_run:
    workflows: ["BE CI PROD"]
    types:
      - completed

jobs:
  cd:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Run deploy.sh on GCP
    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.YOUTIL_PROD_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Run Remote Deploy Script
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.YOUTIL_PROD_HOST }} \
          "bash /home/ubuntu/scripts/be/deploy.sh"