name: BE CI DEV

on:
  push:
    branches:
      - dev

jobs:
  ci:
    name: CI - Build Spring Boot & Upload to GCP
    runs-on: ubuntu-latest

    steps:
      - name: Set Version Timestamp (KST)
        run: echo "VERSION=$(TZ=Asia/Seoul date +'%Y%m%d-%H%M')" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Decode application.yml & gcp credential files
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.YOUTIL_DEV_STORAGE }}" | base64 --decode > src/main/resources/youtil-dev-storage.json
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_DEV_YML }}" | base64 --decode > src/main/resources/application-dev.yml

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build Spring Boot App
        run: ./gradlew clean build -x test

      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.YOUTIL_DEV_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Upload JAR to GCP
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.YOUTIL_DEV_HOST }} \
            "mkdir -p /home/ubuntu/deploy/be/${{ env.VERSION }}"
          scp -i key.pem -o StrictHostKeyChecking=no \
            build/libs/youtil-0.0.1-SNAPSHOT.jar \
            ubuntu@${{ secrets.YOUTIL_DEV_HOST }}:/home/ubuntu/deploy/be/${{ env.VERSION }}/

      - name: Link Latest on Server
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.YOUTIL_DEV_HOST }} \
            "ln -sfn /home/ubuntu/deploy/be/${{ env.VERSION }} /home/ubuntu/deploy/be/latest"

      - name: Clean Old Versions on Server
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.YOUTIL_DEV_HOST }} \
            "cd /home/ubuntu/deploy/be && ls -dt 202* | tail -n +6 | xargs rm -rf || true"