name: BE Deploy to Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Upload & Trigger BE Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Run Remote Deploy Script
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.GCP_USER }}@${{ secrets.GCP_HOST }} << EOF
            export APPLICATION_YML="${{ secrets.APPLICATION_YML }}"
            export APPLICATION_DEV_YML="${{ secrets.APPLICATION_DEV_YML }}"
            bash /home/ubuntu/scripts/be/deploy.sh
EOF
