name: BE Docker CD Dev

on:
  workflow_run:
    workflows: ["BE Docker CI Dev"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    name: Deploy to GCP VM
    runs-on: ubuntu-latest

    steps:
      - name: Set Image Tag
        run: echo "IMAGE_TAG=asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/youtil-docker-registry/youtil-be-dev:latest" >> $GITHUB_ENV
             echo "IMAGE_TAG=asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/youtil-docker-registry/youtil-be-dev:stable" >> $GITHUB_ENV

      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.YOUTIL_DEV_SSH_KEY }}" > key.pem
          chmod 600 key.pem

          - name: Deploy via SSH with Rollback
          run: |
            ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.YOUTIL_DEV_HOST }} << 'EOF'
              set -e
              docker pull ${{ env.LATEST_IMAGE }}
  
              docker stop youtil-be-dev || true
              docker rm youtil-be-dev || true
              docker run -d --name youtil-be-dev \
              -p 8080:8080 \
              ${{ env.IMAGE_TAG }}
            EOF
