name: BE Docker CD Dev

on:
  workflow_run:
    workflows: ["BE Docker CI Dev"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    name: Deploy to GCP VM
    runs-on: ubuntu-latest

    steps:
      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.YOUTIL_DEV_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Copy and Run Deploy Script
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.YOUTIL_DEV_HOST }} "bash /home/ubuntu/scripts/be/deploy.sh"
