name: BE Docker CD Dev

on:
  workflow_run:
    workflows: ["BE Docker CI Dev"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    name: Deploy to GCP VM
    runs-on: ubuntu-latest

    steps:
      - name: Set Image Tag
        run: echo "IMAGE_TAG=asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/youtil-docker-registry/youtil-be-dev:latest" >> $GITHUB_ENV

      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.YOUTIL_DEV_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy via SSH with Rollback
        run: |
          IMAGE_TAG="asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/youtil-docker-registry/youtil-be-dev:latest"
      
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.YOUTIL_DEV_HOST }} \
          IMAGE_TAG=$IMAGE_TAG \
          OTEL_EXPORTER_OTLP_ENDPOINT=https://ingest.us.signoz.cloud:443 \
          OTEL_EXPORTER_OTLP_HEADERS="signoz-access-token=${{ secrets.SIGNOZ_ACCESS_TOKEN }}" \
          OTEL_SERVICE_NAME="youtil-be-dev" \
          'bash -s' << 'EOF'
            set -e
            echo "Using IMAGE_TAG: $IMAGE_TAG"
      
            docker pull $IMAGE_TAG
            docker stop youtil-be-dev || true
            docker rm youtil-be-dev || true
            docker run -d --name youtil-be-dev \
              -p 8080:8080 \
              -e OTEL_EXPORTER_OTLP_ENDPOINT="$OTEL_EXPORTER_OTLP_ENDPOINT" \
              -e OTEL_EXPORTER_OTLP_HEADERS="$OTEL_EXPORTER_OTLP_HEADERS" \
              -e OTEL_SERVICE_NAME="$OTEL_SERVICE_NAME" \
              $IMAGE_TAG \
              --spring.profiles.active=dev
          EOF

      - name: Clean up old Docker images
        run: |
          docker image prune -af